// Automatically generated by astro-icon
// 701a4e065e03a4b2390b9f9f461778ccc258632e9f9efa3e2b5a694e6e655212

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "ri:home-4-line"
		| "ri:github-line"
		| "ri:mastodon-line"
		| "ri:bluesky-fill";
}