// Automatically generated by astro-icon
// 4aad73dc68509a8296eb1b0570cdf1500fa0d373e146e49a18aaac4b69ff0cbe

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "ri:home-4-line"
		| "ri:github-line"
		| "ri:mastodon-line"
		| "ri:bluesky-fill"
		| "ri:quill-pen-fill";
}