// Automatically generated by astro-icon
// 48e1d65fbb7cfceb1ab744973591b135781a08e37211a1c398dbbceee041b2e7

declare module 'virtual:astro-icon' {
  export type Icon = 'ri:github-line' | 'ri:mastodon-line' | 'ri:bluesky-fill';
}
